import { randomUUID } from "node:crypto";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { execute, query, type RowDataPacket } from "@/lib/db";

// Uploaded files live outside /public and are served by /api/uploads/[...path]
export const UPLOAD_ROOT = path.join(process.cwd(), "uploads");

export const MAX_IMAGE_BYTES = 2 * 1024 * 1024; // 2 MB

type ImageType = { ext: "png" | "jpg" | "webp"; mime: string };

// Detect the real type from the file's first bytes instead of trusting the browser
function sniffImage(buf: Buffer): ImageType | null {
  if (buf.length > 8 && buf.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) {
    return { ext: "png", mime: "image/png" };
  }
  if (buf.length > 3 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) {
    return { ext: "jpg", mime: "image/jpeg" };
  }
  if (
    buf.length > 12 &&
    buf.subarray(0, 4).toString("ascii") === "RIFF" &&
    buf.subarray(8, 12).toString("ascii") === "WEBP"
  ) {
    return { ext: "webp", mime: "image/webp" };
  }
  return null;
}

export class UploadError extends Error {}

export const MAX_CV_BYTES = 5 * 1024 * 1024; // 5 MB

/** Saves a PDF (CV) upload to disk, records it in `files`, and returns its id and URL. */
export async function saveCv(
  file: File,
  ownerId: string
): Promise<{ id: string; url: string }> {
  if (file.size === 0) throw new UploadError("The CV file is empty.");
  if (file.size > MAX_CV_BYTES) throw new UploadError("CV must be 5 MB or smaller.");

  const buf = Buffer.from(await file.arrayBuffer());
  if (buf.subarray(0, 5).toString("ascii") !== "%PDF-") {
    throw new UploadError("The CV must be a PDF file.");
  }

  const id = randomUUID();
  const name = `${id}.pdf`;
  const storageKey = `cvs/${name}`;

  await mkdir(path.join(UPLOAD_ROOT, "cvs"), { recursive: true });
  await writeFile(path.join(UPLOAD_ROOT, "cvs", name), buf);

  const url = `/api/uploads/${storageKey}`;
  await execute(
    `INSERT INTO files (id, owner_id, kind, storage_key, url, original_name, mime_type, size_bytes)
     VALUES (?, ?, 'cv', ?, ?, ?, 'application/pdf', ?)`,
    [id, ownerId, storageKey, url, file.name.slice(0, 255), buf.length]
  );
  return { id, url };
}

/** Saves an image upload to disk, records it in `files`, and returns its id and URL. */
export async function saveImage(
  file: File,
  ownerId: string,
  kind: "avatar" | "cover" | "logo" | "work_media"
): Promise<{ id: string; url: string }> {
  if (file.size === 0) throw new UploadError("The image file is empty.");
  if (file.size > MAX_IMAGE_BYTES) throw new UploadError("Image must be 2 MB or smaller.");

  const buf = Buffer.from(await file.arrayBuffer());
  const type = sniffImage(buf);
  if (!type) throw new UploadError("Only PNG, JPG or WebP images are allowed.");

  const id = randomUUID();
  const folder = `${kind}s`;
  const name = `${id}.${type.ext}`;
  const storageKey = `${folder}/${name}`;

  await mkdir(path.join(UPLOAD_ROOT, folder), { recursive: true });
  await writeFile(path.join(UPLOAD_ROOT, folder, name), buf);

  const url = `/api/uploads/${storageKey}`;
  await execute(
    `INSERT INTO files (id, owner_id, kind, storage_key, url, original_name, mime_type, size_bytes)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
    [id, ownerId, kind, storageKey, url, file.name.slice(0, 255), type.mime, buf.length]
  );
  return { id, url };
}

/** Deletes uploaded files: their database rows and the bytes on disk. Missing files are ignored. */
export async function removeFiles(ids: string[]): Promise<void> {
  if (ids.length === 0) return;
  const rows = await query<RowDataPacket & { storage_key: string }>(
    "SELECT storage_key FROM files WHERE id IN (?)",
    [ids]
  );
  await execute("DELETE FROM files WHERE id IN (?)", [ids]);
  for (const row of rows) {
    // storage keys are generated by us (<folder>/<uuid>.<ext>); never follow anything else
    if (!/^[a-z_]+\/[0-9a-f-]{36}(\.(png|jpg|webp|pdf))?$/.test(row.storage_key)) continue;
    await unlink(path.join(UPLOAD_ROOT, row.storage_key)).catch(() => {});
  }
}

export const MAX_RECEIPT_BYTES = 5 * 1024 * 1024; // 5 MB

/**
 * Saves a transfer receipt (photo or PDF). Receipts are private: they live in their own folder,
 * which /api/uploads never serves. They are shown only through /api/payments/[id]/receipt,
 * to the client who paid and to admins.
 */
export async function saveReceipt(file: File, ownerId: string): Promise<{ id: string }> {
  if (file.size === 0) throw new UploadError("The receipt file is empty.");
  if (file.size > MAX_RECEIPT_BYTES) throw new UploadError("The receipt must be 5 MB or smaller.");

  const buf = Buffer.from(await file.arrayBuffer());
  const isPdf = buf.subarray(0, 5).toString("ascii") === "%PDF-";
  const image = isPdf ? null : sniffImage(buf);
  if (!isPdf && !image) throw new UploadError("The receipt must be a photo (PNG, JPG, WebP) or a PDF.");

  const ext = isPdf ? "pdf" : image!.ext;
  const mime = isPdf ? "application/pdf" : image!.mime;
  const id = randomUUID();
  const storageKey = `receipts/${id}.${ext}`;

  await mkdir(path.join(UPLOAD_ROOT, "receipts"), { recursive: true });
  await writeFile(path.join(UPLOAD_ROOT, "receipts", `${id}.${ext}`), buf);
  await execute(
    `INSERT INTO files (id, owner_id, kind, storage_key, url, original_name, mime_type, size_bytes)
     VALUES (?, ?, 'payment_receipt', ?, ?, ?, ?, ?)`,
    [id, ownerId, storageKey, `private:${storageKey}`, file.name.slice(0, 255), mime, buf.length]
  );
  return { id };
}
